spring.application.name=projeto-livraria

# Use variável de ambiente em produção para não expor senha no GitHub.
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/livraria}
spring.data.mongodb.database=livraria

spring.thymeleaf.cache=false
server.error.include-message=always
viacep.base-url=https://viacep.com.br/ws/